### ISSUE TITLE
Example.env update

### ISSUE THREAD

**Issue by Demidog03** [hmake98/nestjs-graphql-starter#3]
In **docker-compose.yml** some env variables is used, however they are not in example.env

```
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_DB: ${POSTGRES_DB:-db}
```

Could you update the example.env?

```
DATABASE_URL=postgresql://username:password@localhost:5432/database_name
➕POSTGRES_USER=username
➕POSTGRES_PASSWORD=password
➕POSTGRES_DB=database_name
```
